# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         DateTime-Event-ICal
version:      0.08
version_from: lib/DateTime/Event/ICal.pm
installdirs:  site
requires:
    DateTime:                      0
    DateTime::Event::Recurrence:   0.11

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
